from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from sovd_server.models.base_model import Model
from sovd_server import util


class ConfigurationWrite(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data=None, signature=None):  # noqa: E501
        """ConfigurationWrite - a model defined in OpenAPI

        :param data: The data of this ConfigurationWrite.  # noqa: E501
        :type data: object
        :param signature: The signature of this ConfigurationWrite.  # noqa: E501
        :type signature: str
        """
        self.openapi_types = {
            'data': object,
            'signature': str
        }

        self.attribute_map = {
            'data': 'data',
            'signature': 'signature'
        }

        self._data = data
        self._signature = signature

    @classmethod
    def from_dict(cls, dikt) -> 'ConfigurationWrite':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ConfigurationWrite of this ConfigurationWrite.  # noqa: E501
        :rtype: ConfigurationWrite
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> object:
        """Gets the data of this ConfigurationWrite.

        Configuration data to write  # noqa: E501

        :return: The data of this ConfigurationWrite.
        :rtype: object
        """
        return self._data

    @data.setter
    def data(self, data: object):
        """Sets the data of this ConfigurationWrite.

        Configuration data to write  # noqa: E501

        :param data: The data of this ConfigurationWrite.
        :type data: object
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data

    @property
    def signature(self) -> str:
        """Gets the signature of this ConfigurationWrite.

        Data signature for verification  # noqa: E501

        :return: The signature of this ConfigurationWrite.
        :rtype: str
        """
        return self._signature

    @signature.setter
    def signature(self, signature: str):
        """Sets the signature of this ConfigurationWrite.

        Data signature for verification  # noqa: E501

        :param signature: The signature of this ConfigurationWrite.
        :type signature: str
        """

        self._signature = signature
