from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from sovd_server.models.base_model import Model
from sovd_server import util


class CyclicSubscriptionReference(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, resource=None, subscription=None, protocol=None):  # noqa: E501
        """CyclicSubscriptionReference - a model defined in OpenAPI

        :param id: The id of this CyclicSubscriptionReference.  # noqa: E501
        :type id: str
        :param resource: The resource of this CyclicSubscriptionReference.  # noqa: E501
        :type resource: str
        :param subscription: The subscription of this CyclicSubscriptionReference.  # noqa: E501
        :type subscription: str
        :param protocol: The protocol of this CyclicSubscriptionReference.  # noqa: E501
        :type protocol: str
        """
        self.openapi_types = {
            'id': str,
            'resource': str,
            'subscription': str,
            'protocol': str
        }

        self.attribute_map = {
            'id': 'id',
            'resource': 'resource',
            'subscription': 'subscription',
            'protocol': 'protocol'
        }

        self._id = id
        self._resource = resource
        self._subscription = subscription
        self._protocol = protocol

    @classmethod
    def from_dict(cls, dikt) -> 'CyclicSubscriptionReference':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CyclicSubscriptionReference of this CyclicSubscriptionReference.  # noqa: E501
        :rtype: CyclicSubscriptionReference
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this CyclicSubscriptionReference.

        Subscription identifier  # noqa: E501

        :return: The id of this CyclicSubscriptionReference.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this CyclicSubscriptionReference.

        Subscription identifier  # noqa: E501

        :param id: The id of this CyclicSubscriptionReference.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def resource(self) -> str:
        """Gets the resource of this CyclicSubscriptionReference.

        Monitored resource URI  # noqa: E501

        :return: The resource of this CyclicSubscriptionReference.
        :rtype: str
        """
        return self._resource

    @resource.setter
    def resource(self, resource: str):
        """Sets the resource of this CyclicSubscriptionReference.

        Monitored resource URI  # noqa: E501

        :param resource: The resource of this CyclicSubscriptionReference.
        :type resource: str
        """
        if resource is None:
            raise ValueError("Invalid value for `resource`, must not be `None`")  # noqa: E501

        self._resource = resource

    @property
    def subscription(self) -> str:
        """Gets the subscription of this CyclicSubscriptionReference.

        Subscription URI  # noqa: E501

        :return: The subscription of this CyclicSubscriptionReference.
        :rtype: str
        """
        return self._subscription

    @subscription.setter
    def subscription(self, subscription: str):
        """Sets the subscription of this CyclicSubscriptionReference.

        Subscription URI  # noqa: E501

        :param subscription: The subscription of this CyclicSubscriptionReference.
        :type subscription: str
        """
        if subscription is None:
            raise ValueError("Invalid value for `subscription`, must not be `None`")  # noqa: E501

        self._subscription = subscription

    @property
    def protocol(self) -> str:
        """Gets the protocol of this CyclicSubscriptionReference.

        Event protocol  # noqa: E501

        :return: The protocol of this CyclicSubscriptionReference.
        :rtype: str
        """
        return self._protocol

    @protocol.setter
    def protocol(self, protocol: str):
        """Sets the protocol of this CyclicSubscriptionReference.

        Event protocol  # noqa: E501

        :param protocol: The protocol of this CyclicSubscriptionReference.
        :type protocol: str
        """
        allowed_values = ["sse"]  # noqa: E501
        if protocol not in allowed_values:
            raise ValueError(
                "Invalid value for `protocol` ({0}), must be one of {1}"
                .format(protocol, allowed_values)
            )

        self._protocol = protocol
