from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from sovd_server.models.base_model import Model
from sovd_server import util


class CyclicSubscriptionCreate(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, resource=None, protocol=None, interval='medium', duration=None):  # noqa: E501
        """CyclicSubscriptionCreate - a model defined in OpenAPI

        :param resource: The resource of this CyclicSubscriptionCreate.  # noqa: E501
        :type resource: str
        :param protocol: The protocol of this CyclicSubscriptionCreate.  # noqa: E501
        :type protocol: str
        :param interval: The interval of this CyclicSubscriptionCreate.  # noqa: E501
        :type interval: str
        :param duration: The duration of this CyclicSubscriptionCreate.  # noqa: E501
        :type duration: int
        """
        self.openapi_types = {
            'resource': str,
            'protocol': str,
            'interval': str,
            'duration': int
        }

        self.attribute_map = {
            'resource': 'resource',
            'protocol': 'protocol',
            'interval': 'interval',
            'duration': 'duration'
        }

        self._resource = resource
        self._protocol = protocol
        self._interval = interval
        self._duration = duration

    @classmethod
    def from_dict(cls, dikt) -> 'CyclicSubscriptionCreate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CyclicSubscriptionCreate of this CyclicSubscriptionCreate.  # noqa: E501
        :rtype: CyclicSubscriptionCreate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def resource(self) -> str:
        """Gets the resource of this CyclicSubscriptionCreate.

        Resource to monitor  # noqa: E501

        :return: The resource of this CyclicSubscriptionCreate.
        :rtype: str
        """
        return self._resource

    @resource.setter
    def resource(self, resource: str):
        """Sets the resource of this CyclicSubscriptionCreate.

        Resource to monitor  # noqa: E501

        :param resource: The resource of this CyclicSubscriptionCreate.
        :type resource: str
        """
        if resource is None:
            raise ValueError("Invalid value for `resource`, must not be `None`")  # noqa: E501

        self._resource = resource

    @property
    def protocol(self) -> str:
        """Gets the protocol of this CyclicSubscriptionCreate.


        :return: The protocol of this CyclicSubscriptionCreate.
        :rtype: str
        """
        return self._protocol

    @protocol.setter
    def protocol(self, protocol: str):
        """Sets the protocol of this CyclicSubscriptionCreate.


        :param protocol: The protocol of this CyclicSubscriptionCreate.
        :type protocol: str
        """
        allowed_values = ["sse"]  # noqa: E501
        if protocol not in allowed_values:
            raise ValueError(
                "Invalid value for `protocol` ({0}), must be one of {1}"
                .format(protocol, allowed_values)
            )

        self._protocol = protocol

    @property
    def interval(self) -> str:
        """Gets the interval of this CyclicSubscriptionCreate.


        :return: The interval of this CyclicSubscriptionCreate.
        :rtype: str
        """
        return self._interval

    @interval.setter
    def interval(self, interval: str):
        """Sets the interval of this CyclicSubscriptionCreate.


        :param interval: The interval of this CyclicSubscriptionCreate.
        :type interval: str
        """
        allowed_values = ["slow", "medium", "fast"]  # noqa: E501
        if interval not in allowed_values:
            raise ValueError(
                "Invalid value for `interval` ({0}), must be one of {1}"
                .format(interval, allowed_values)
            )

        self._interval = interval

    @property
    def duration(self) -> int:
        """Gets the duration of this CyclicSubscriptionCreate.

        Subscription duration in seconds  # noqa: E501

        :return: The duration of this CyclicSubscriptionCreate.
        :rtype: int
        """
        return self._duration

    @duration.setter
    def duration(self, duration: int):
        """Sets the duration of this CyclicSubscriptionCreate.

        Subscription duration in seconds  # noqa: E501

        :param duration: The duration of this CyclicSubscriptionCreate.
        :type duration: int
        """

        self._duration = duration
