from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from sovd_server.models.base_model import Model
from sovd_server.models.cyclic_subscription_reference import CyclicSubscriptionReference
from sovd_server import util

from sovd_server.models.cyclic_subscription_reference import CyclicSubscriptionReference  # noqa: E501

class CyclicSubscriptionCollection(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, items=None):  # noqa: E501
        """CyclicSubscriptionCollection - a model defined in OpenAPI

        :param items: The items of this CyclicSubscriptionCollection.  # noqa: E501
        :type items: List[CyclicSubscriptionReference]
        """
        self.openapi_types = {
            'items': List[CyclicSubscriptionReference]
        }

        self.attribute_map = {
            'items': 'items'
        }

        self._items = items

    @classmethod
    def from_dict(cls, dikt) -> 'CyclicSubscriptionCollection':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CyclicSubscriptionCollection of this CyclicSubscriptionCollection.  # noqa: E501
        :rtype: CyclicSubscriptionCollection
        """
        return util.deserialize_model(dikt, cls)

    @property
    def items(self) -> List[CyclicSubscriptionReference]:
        """Gets the items of this CyclicSubscriptionCollection.


        :return: The items of this CyclicSubscriptionCollection.
        :rtype: List[CyclicSubscriptionReference]
        """
        return self._items

    @items.setter
    def items(self, items: List[CyclicSubscriptionReference]):
        """Sets the items of this CyclicSubscriptionCollection.


        :param items: The items of this CyclicSubscriptionCollection.
        :type items: List[CyclicSubscriptionReference]
        """
        if items is None:
            raise ValueError("Invalid value for `items`, must not be `None`")  # noqa: E501

        self._items = items
