from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from sovd_server.models.base_model import Model
from sovd_server import util


class CyclicSubscriptionUpdate(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, interval=None, duration=None):  # noqa: E501
        """CyclicSubscriptionUpdate - a model defined in OpenAPI

        :param interval: The interval of this CyclicSubscriptionUpdate.  # noqa: E501
        :type interval: str
        :param duration: The duration of this CyclicSubscriptionUpdate.  # noqa: E501
        :type duration: int
        """
        self.openapi_types = {
            'interval': str,
            'duration': int
        }

        self.attribute_map = {
            'interval': 'interval',
            'duration': 'duration'
        }

        self._interval = interval
        self._duration = duration

    @classmethod
    def from_dict(cls, dikt) -> 'CyclicSubscriptionUpdate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CyclicSubscriptionUpdate of this CyclicSubscriptionUpdate.  # noqa: E501
        :rtype: CyclicSubscriptionUpdate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def interval(self) -> str:
        """Gets the interval of this CyclicSubscriptionUpdate.


        :return: The interval of this CyclicSubscriptionUpdate.
        :rtype: str
        """
        return self._interval

    @interval.setter
    def interval(self, interval: str):
        """Sets the interval of this CyclicSubscriptionUpdate.


        :param interval: The interval of this CyclicSubscriptionUpdate.
        :type interval: str
        """
        allowed_values = ["slow", "medium", "fast"]  # noqa: E501
        if interval not in allowed_values:
            raise ValueError(
                "Invalid value for `interval` ({0}), must be one of {1}"
                .format(interval, allowed_values)
            )

        self._interval = interval

    @property
    def duration(self) -> int:
        """Gets the duration of this CyclicSubscriptionUpdate.

        Subscription duration in seconds  # noqa: E501

        :return: The duration of this CyclicSubscriptionUpdate.
        :rtype: int
        """
        return self._duration

    @duration.setter
    def duration(self, duration: int):
        """Sets the duration of this CyclicSubscriptionUpdate.

        Subscription duration in seconds  # noqa: E501

        :param duration: The duration of this CyclicSubscriptionUpdate.
        :type duration: int
        """

        self._duration = duration
