from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from sovd_server.models.base_model import Model
from sovd_server import util


class DataResource(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, name=None, data=None, _schema=None, tags=None):  # noqa: E501
        """DataResource - a model defined in OpenAPI

        :param id: The id of this DataResource.  # noqa: E501
        :type id: str
        :param name: The name of this DataResource.  # noqa: E501
        :type name: str
        :param data: The data of this DataResource.  # noqa: E501
        :type data: object
        :param _schema: The _schema of this DataResource.  # noqa: E501
        :type _schema: object
        :param tags: The tags of this DataResource.  # noqa: E501
        :type tags: List[str]
        """
        self.openapi_types = {
            'id': str,
            'name': str,
            'data': object,
            '_schema': object,
            'tags': List[str]
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'data': 'data',
            '_schema': 'schema',
            'tags': 'tags'
        }

        self._id = id
        self._name = name
        self._data = data
        self.__schema = _schema
        self._tags = tags

    @classmethod
    def from_dict(cls, dikt) -> 'DataResource':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DataResource of this DataResource.  # noqa: E501
        :rtype: DataResource
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this DataResource.


        :return: The id of this DataResource.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this DataResource.


        :param id: The id of this DataResource.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this DataResource.


        :return: The name of this DataResource.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this DataResource.


        :param name: The name of this DataResource.
        :type name: str
        """

        self._name = name

    @property
    def data(self) -> object:
        """Gets the data of this DataResource.

        Data value  # noqa: E501

        :return: The data of this DataResource.
        :rtype: object
        """
        return self._data

    @data.setter
    def data(self, data: object):
        """Sets the data of this DataResource.

        Data value  # noqa: E501

        :param data: The data of this DataResource.
        :type data: object
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data

    @property
    def _schema(self) -> object:
        """Gets the _schema of this DataResource.

        JSON schema for the data  # noqa: E501

        :return: The _schema of this DataResource.
        :rtype: object
        """
        return self.__schema

    @_schema.setter
    def _schema(self, _schema: object):
        """Sets the _schema of this DataResource.

        JSON schema for the data  # noqa: E501

        :param _schema: The _schema of this DataResource.
        :type _schema: object
        """

        self.__schema = _schema

    @property
    def tags(self) -> List[str]:
        """Gets the tags of this DataResource.


        :return: The tags of this DataResource.
        :rtype: List[str]
        """
        return self._tags

    @tags.setter
    def tags(self, tags: List[str]):
        """Sets the tags of this DataResource.


        :param tags: The tags of this DataResource.
        :type tags: List[str]
        """

        self._tags = tags
