from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from sovd_server.models.base_model import Model
from sovd_server import util


class DataResourceWrite(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, data=None):  # noqa: E501
        """DataResourceWrite - a model defined in OpenAPI

        :param data: The data of this DataResourceWrite.  # noqa: E501
        :type data: object
        """
        self.openapi_types = {
            'data': object
        }

        self.attribute_map = {
            'data': 'data'
        }

        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'DataResourceWrite':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DataResourceWrite of this DataResourceWrite.  # noqa: E501
        :rtype: DataResourceWrite
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> object:
        """Gets the data of this DataResourceWrite.

        Data value to write  # noqa: E501

        :return: The data of this DataResourceWrite.
        :rtype: object
        """
        return self._data

    @data.setter
    def data(self, data: object):
        """Sets the data of this DataResourceWrite.

        Data value to write  # noqa: E501

        :param data: The data of this DataResourceWrite.
        :type data: object
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data
