from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from sovd_server.models.base_model import Model
from sovd_server import util


class EntityCapabilities(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, name=None, tags=None, data=None, faults=None, operations=None, configurations=None, modes=None):  # noqa: E501
        """EntityCapabilities - a model defined in OpenAPI

        :param id: The id of this EntityCapabilities.  # noqa: E501
        :type id: str
        :param name: The name of this EntityCapabilities.  # noqa: E501
        :type name: str
        :param tags: The tags of this EntityCapabilities.  # noqa: E501
        :type tags: List[str]
        :param data: The data of this EntityCapabilities.  # noqa: E501
        :type data: str
        :param faults: The faults of this EntityCapabilities.  # noqa: E501
        :type faults: str
        :param operations: The operations of this EntityCapabilities.  # noqa: E501
        :type operations: str
        :param configurations: The configurations of this EntityCapabilities.  # noqa: E501
        :type configurations: str
        :param modes: The modes of this EntityCapabilities.  # noqa: E501
        :type modes: str
        """
        self.openapi_types = {
            'id': str,
            'name': str,
            'tags': List[str],
            'data': str,
            'faults': str,
            'operations': str,
            'configurations': str,
            'modes': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'tags': 'tags',
            'data': 'data',
            'faults': 'faults',
            'operations': 'operations',
            'configurations': 'configurations',
            'modes': 'modes'
        }

        self._id = id
        self._name = name
        self._tags = tags
        self._data = data
        self._faults = faults
        self._operations = operations
        self._configurations = configurations
        self._modes = modes

    @classmethod
    def from_dict(cls, dikt) -> 'EntityCapabilities':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EntityCapabilities of this EntityCapabilities.  # noqa: E501
        :rtype: EntityCapabilities
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this EntityCapabilities.

        Entity identifier  # noqa: E501

        :return: The id of this EntityCapabilities.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this EntityCapabilities.

        Entity identifier  # noqa: E501

        :param id: The id of this EntityCapabilities.
        :type id: str
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this EntityCapabilities.

        Entity name  # noqa: E501

        :return: The name of this EntityCapabilities.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this EntityCapabilities.

        Entity name  # noqa: E501

        :param name: The name of this EntityCapabilities.
        :type name: str
        """

        self._name = name

    @property
    def tags(self) -> List[str]:
        """Gets the tags of this EntityCapabilities.


        :return: The tags of this EntityCapabilities.
        :rtype: List[str]
        """
        return self._tags

    @tags.setter
    def tags(self, tags: List[str]):
        """Sets the tags of this EntityCapabilities.


        :param tags: The tags of this EntityCapabilities.
        :type tags: List[str]
        """

        self._tags = tags

    @property
    def data(self) -> str:
        """Gets the data of this EntityCapabilities.

        Data resources URI  # noqa: E501

        :return: The data of this EntityCapabilities.
        :rtype: str
        """
        return self._data

    @data.setter
    def data(self, data: str):
        """Sets the data of this EntityCapabilities.

        Data resources URI  # noqa: E501

        :param data: The data of this EntityCapabilities.
        :type data: str
        """

        self._data = data

    @property
    def faults(self) -> str:
        """Gets the faults of this EntityCapabilities.

        Faults URI  # noqa: E501

        :return: The faults of this EntityCapabilities.
        :rtype: str
        """
        return self._faults

    @faults.setter
    def faults(self, faults: str):
        """Sets the faults of this EntityCapabilities.

        Faults URI  # noqa: E501

        :param faults: The faults of this EntityCapabilities.
        :type faults: str
        """

        self._faults = faults

    @property
    def operations(self) -> str:
        """Gets the operations of this EntityCapabilities.

        Operations URI  # noqa: E501

        :return: The operations of this EntityCapabilities.
        :rtype: str
        """
        return self._operations

    @operations.setter
    def operations(self, operations: str):
        """Sets the operations of this EntityCapabilities.

        Operations URI  # noqa: E501

        :param operations: The operations of this EntityCapabilities.
        :type operations: str
        """

        self._operations = operations

    @property
    def configurations(self) -> str:
        """Gets the configurations of this EntityCapabilities.

        Configurations URI  # noqa: E501

        :return: The configurations of this EntityCapabilities.
        :rtype: str
        """
        return self._configurations

    @configurations.setter
    def configurations(self, configurations: str):
        """Sets the configurations of this EntityCapabilities.

        Configurations URI  # noqa: E501

        :param configurations: The configurations of this EntityCapabilities.
        :type configurations: str
        """

        self._configurations = configurations

    @property
    def modes(self) -> str:
        """Gets the modes of this EntityCapabilities.

        Modes URI  # noqa: E501

        :return: The modes of this EntityCapabilities.
        :rtype: str
        """
        return self._modes

    @modes.setter
    def modes(self, modes: str):
        """Sets the modes of this EntityCapabilities.

        Modes URI  # noqa: E501

        :param modes: The modes of this EntityCapabilities.
        :type modes: str
        """

        self._modes = modes
