from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from sovd_server.models.base_model import Model
from sovd_server.models.entity_reference import EntityReference
from sovd_server import util

from sovd_server.models.entity_reference import EntityReference  # noqa: E501

class EntityCollection(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, items=None):  # noqa: E501
        """EntityCollection - a model defined in OpenAPI

        :param items: The items of this EntityCollection.  # noqa: E501
        :type items: List[EntityReference]
        """
        self.openapi_types = {
            'items': List[EntityReference]
        }

        self.attribute_map = {
            'items': 'items'
        }

        self._items = items

    @classmethod
    def from_dict(cls, dikt) -> 'EntityCollection':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EntityCollection of this EntityCollection.  # noqa: E501
        :rtype: EntityCollection
        """
        return util.deserialize_model(dikt, cls)

    @property
    def items(self) -> List[EntityReference]:
        """Gets the items of this EntityCollection.


        :return: The items of this EntityCollection.
        :rtype: List[EntityReference]
        """
        return self._items

    @items.setter
    def items(self, items: List[EntityReference]):
        """Sets the items of this EntityCollection.


        :param items: The items of this EntityCollection.
        :type items: List[EntityReference]
        """
        if items is None:
            raise ValueError("Invalid value for `items`, must not be `None`")  # noqa: E501

        self._items = items
