from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from sovd_server.models.base_model import Model
from sovd_server.models.extended_data_records import ExtendedDataRecords
from sovd_server.models.snapshot import Snapshot
from sovd_server import util

from sovd_server.models.extended_data_records import ExtendedDataRecords  # noqa: E501
from sovd_server.models.snapshot import Snapshot  # noqa: E501

class EnvironmentData(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, extended_data_records=None, snapshots=None):  # noqa: E501
        """EnvironmentData - a model defined in OpenAPI

        :param extended_data_records: The extended_data_records of this EnvironmentData.  # noqa: E501
        :type extended_data_records: ExtendedDataRecords
        :param snapshots: The snapshots of this EnvironmentData.  # noqa: E501
        :type snapshots: List[Snapshot]
        """
        self.openapi_types = {
            'extended_data_records': ExtendedDataRecords,
            'snapshots': List[Snapshot]
        }

        self.attribute_map = {
            'extended_data_records': 'extended_data_records',
            'snapshots': 'snapshots'
        }

        self._extended_data_records = extended_data_records
        self._snapshots = snapshots

    @classmethod
    def from_dict(cls, dikt) -> 'EnvironmentData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EnvironmentData of this EnvironmentData.  # noqa: E501
        :rtype: EnvironmentData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def extended_data_records(self) -> ExtendedDataRecords:
        """Gets the extended_data_records of this EnvironmentData.


        :return: The extended_data_records of this EnvironmentData.
        :rtype: ExtendedDataRecords
        """
        return self._extended_data_records

    @extended_data_records.setter
    def extended_data_records(self, extended_data_records: ExtendedDataRecords):
        """Sets the extended_data_records of this EnvironmentData.


        :param extended_data_records: The extended_data_records of this EnvironmentData.
        :type extended_data_records: ExtendedDataRecords
        """

        self._extended_data_records = extended_data_records

    @property
    def snapshots(self) -> List[Snapshot]:
        """Gets the snapshots of this EnvironmentData.


        :return: The snapshots of this EnvironmentData.
        :rtype: List[Snapshot]
        """
        return self._snapshots

    @snapshots.setter
    def snapshots(self, snapshots: List[Snapshot]):
        """Sets the snapshots of this EnvironmentData.


        :param snapshots: The snapshots of this EnvironmentData.
        :type snapshots: List[Snapshot]
        """

        self._snapshots = snapshots
