from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from sovd_server.models.base_model import Model
from sovd_server.models.fault_reference import FaultReference
from sovd_server import util

from sovd_server.models.fault_reference import FaultReference  # noqa: E501

class FaultCollection(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, items=None):  # noqa: E501
        """FaultCollection - a model defined in OpenAPI

        :param items: The items of this FaultCollection.  # noqa: E501
        :type items: List[FaultReference]
        """
        self.openapi_types = {
            'items': List[FaultReference]
        }

        self.attribute_map = {
            'items': 'items'
        }

        self._items = items

    @classmethod
    def from_dict(cls, dikt) -> 'FaultCollection':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FaultCollection of this FaultCollection.  # noqa: E501
        :rtype: FaultCollection
        """
        return util.deserialize_model(dikt, cls)

    @property
    def items(self) -> List[FaultReference]:
        """Gets the items of this FaultCollection.


        :return: The items of this FaultCollection.
        :rtype: List[FaultReference]
        """
        return self._items

    @items.setter
    def items(self, items: List[FaultReference]):
        """Sets the items of this FaultCollection.


        :param items: The items of this FaultCollection.
        :type items: List[FaultReference]
        """
        if items is None:
            raise ValueError("Invalid value for `items`, must not be `None`")  # noqa: E501

        self._items = items
