from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from sovd_server.models.base_model import Model
from sovd_server.models.environment_data import EnvironmentData
from sovd_server.models.fault_reference import FaultReference
from sovd_server import util

from sovd_server.models.environment_data import EnvironmentData  # noqa: E501
from sovd_server.models.fault_reference import FaultReference  # noqa: E501

class Fault(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, item=None, environment_data=None):  # noqa: E501
        """Fault - a model defined in OpenAPI

        :param item: The item of this Fault.  # noqa: E501
        :type item: FaultReference
        :param environment_data: The environment_data of this Fault.  # noqa: E501
        :type environment_data: EnvironmentData
        """
        self.openapi_types = {
            'item': FaultReference,
            'environment_data': EnvironmentData
        }

        self.attribute_map = {
            'item': 'item',
            'environment_data': 'environment_data'
        }

        self._item = item
        self._environment_data = environment_data

    @classmethod
    def from_dict(cls, dikt) -> 'Fault':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Fault of this Fault.  # noqa: E501
        :rtype: Fault
        """
        return util.deserialize_model(dikt, cls)

    @property
    def item(self) -> FaultReference:
        """Gets the item of this Fault.


        :return: The item of this Fault.
        :rtype: FaultReference
        """
        return self._item

    @item.setter
    def item(self, item: FaultReference):
        """Sets the item of this Fault.


        :param item: The item of this Fault.
        :type item: FaultReference
        """
        if item is None:
            raise ValueError("Invalid value for `item`, must not be `None`")  # noqa: E501

        self._item = item

    @property
    def environment_data(self) -> EnvironmentData:
        """Gets the environment_data of this Fault.


        :return: The environment_data of this Fault.
        :rtype: EnvironmentData
        """
        return self._environment_data

    @environment_data.setter
    def environment_data(self, environment_data: EnvironmentData):
        """Sets the environment_data of this Fault.


        :param environment_data: The environment_data of this Fault.
        :type environment_data: EnvironmentData
        """
        if environment_data is None:
            raise ValueError("Invalid value for `environment_data`, must not be `None`")  # noqa: E501

        self._environment_data = environment_data
