from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from sovd_server.models.base_model import Model
from sovd_server.models.fault_status import FaultStatus
from sovd_server import util

from sovd_server.models.fault_status import FaultStatus  # noqa: E501

class FaultReference(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, code=None, scope=None, display_code=None, fault_name=None, fault_translation_id=None, severity=None, status=None):  # noqa: E501
        """FaultReference - a model defined in OpenAPI

        :param code: The code of this FaultReference.  # noqa: E501
        :type code: str
        :param scope: The scope of this FaultReference.  # noqa: E501
        :type scope: str
        :param display_code: The display_code of this FaultReference.  # noqa: E501
        :type display_code: str
        :param fault_name: The fault_name of this FaultReference.  # noqa: E501
        :type fault_name: str
        :param fault_translation_id: The fault_translation_id of this FaultReference.  # noqa: E501
        :type fault_translation_id: str
        :param severity: The severity of this FaultReference.  # noqa: E501
        :type severity: int
        :param status: The status of this FaultReference.  # noqa: E501
        :type status: FaultStatus
        """
        self.openapi_types = {
            'code': str,
            'scope': str,
            'display_code': str,
            'fault_name': str,
            'fault_translation_id': str,
            'severity': int,
            'status': FaultStatus
        }

        self.attribute_map = {
            'code': 'code',
            'scope': 'scope',
            'display_code': 'display_code',
            'fault_name': 'fault_name',
            'fault_translation_id': 'fault_translation_id',
            'severity': 'severity',
            'status': 'status'
        }

        self._code = code
        self._scope = scope
        self._display_code = display_code
        self._fault_name = fault_name
        self._fault_translation_id = fault_translation_id
        self._severity = severity
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'FaultReference':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FaultReference of this FaultReference.  # noqa: E501
        :rtype: FaultReference
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> str:
        """Gets the code of this FaultReference.

        Fault code  # noqa: E501

        :return: The code of this FaultReference.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code: str):
        """Sets the code of this FaultReference.

        Fault code  # noqa: E501

        :param code: The code of this FaultReference.
        :type code: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def scope(self) -> str:
        """Gets the scope of this FaultReference.

        Fault scope  # noqa: E501

        :return: The scope of this FaultReference.
        :rtype: str
        """
        return self._scope

    @scope.setter
    def scope(self, scope: str):
        """Sets the scope of this FaultReference.

        Fault scope  # noqa: E501

        :param scope: The scope of this FaultReference.
        :type scope: str
        """
        if scope is None:
            raise ValueError("Invalid value for `scope`, must not be `None`")  # noqa: E501

        self._scope = scope

    @property
    def display_code(self) -> str:
        """Gets the display_code of this FaultReference.

        Display code  # noqa: E501

        :return: The display_code of this FaultReference.
        :rtype: str
        """
        return self._display_code

    @display_code.setter
    def display_code(self, display_code: str):
        """Sets the display_code of this FaultReference.

        Display code  # noqa: E501

        :param display_code: The display_code of this FaultReference.
        :type display_code: str
        """

        self._display_code = display_code

    @property
    def fault_name(self) -> str:
        """Gets the fault_name of this FaultReference.

        Fault name  # noqa: E501

        :return: The fault_name of this FaultReference.
        :rtype: str
        """
        return self._fault_name

    @fault_name.setter
    def fault_name(self, fault_name: str):
        """Sets the fault_name of this FaultReference.

        Fault name  # noqa: E501

        :param fault_name: The fault_name of this FaultReference.
        :type fault_name: str
        """
        if fault_name is None:
            raise ValueError("Invalid value for `fault_name`, must not be `None`")  # noqa: E501

        self._fault_name = fault_name

    @property
    def fault_translation_id(self) -> str:
        """Gets the fault_translation_id of this FaultReference.

        Translation ID  # noqa: E501

        :return: The fault_translation_id of this FaultReference.
        :rtype: str
        """
        return self._fault_translation_id

    @fault_translation_id.setter
    def fault_translation_id(self, fault_translation_id: str):
        """Sets the fault_translation_id of this FaultReference.

        Translation ID  # noqa: E501

        :param fault_translation_id: The fault_translation_id of this FaultReference.
        :type fault_translation_id: str
        """

        self._fault_translation_id = fault_translation_id

    @property
    def severity(self) -> int:
        """Gets the severity of this FaultReference.

        Severity level  # noqa: E501

        :return: The severity of this FaultReference.
        :rtype: int
        """
        return self._severity

    @severity.setter
    def severity(self, severity: int):
        """Sets the severity of this FaultReference.

        Severity level  # noqa: E501

        :param severity: The severity of this FaultReference.
        :type severity: int
        """
        if severity is None:
            raise ValueError("Invalid value for `severity`, must not be `None`")  # noqa: E501
        if severity is not None and severity > 3:  # noqa: E501
            raise ValueError("Invalid value for `severity`, must be a value less than or equal to `3`")  # noqa: E501
        if severity is not None and severity < 1:  # noqa: E501
            raise ValueError("Invalid value for `severity`, must be a value greater than or equal to `1`")  # noqa: E501

        self._severity = severity

    @property
    def status(self) -> FaultStatus:
        """Gets the status of this FaultReference.


        :return: The status of this FaultReference.
        :rtype: FaultStatus
        """
        return self._status

    @status.setter
    def status(self, status: FaultStatus):
        """Sets the status of this FaultReference.


        :param status: The status of this FaultReference.
        :type status: FaultStatus
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status
