from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from sovd_server.models.base_model import Model
from sovd_server import util


class ModeSet(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, value=None, mode_expiration=None):  # noqa: E501
        """ModeSet - a model defined in OpenAPI

        :param value: The value of this ModeSet.  # noqa: E501
        :type value: str
        :param mode_expiration: The mode_expiration of this ModeSet.  # noqa: E501
        :type mode_expiration: int
        """
        self.openapi_types = {
            'value': str,
            'mode_expiration': int
        }

        self.attribute_map = {
            'value': 'value',
            'mode_expiration': 'mode_expiration'
        }

        self._value = value
        self._mode_expiration = mode_expiration

    @classmethod
    def from_dict(cls, dikt) -> 'ModeSet':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ModeSet of this ModeSet.  # noqa: E501
        :rtype: ModeSet
        """
        return util.deserialize_model(dikt, cls)

    @property
    def value(self) -> str:
        """Gets the value of this ModeSet.

        Mode value to set  # noqa: E501

        :return: The value of this ModeSet.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value: str):
        """Sets the value of this ModeSet.

        Mode value to set  # noqa: E501

        :param value: The value of this ModeSet.
        :type value: str
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value

    @property
    def mode_expiration(self) -> int:
        """Gets the mode_expiration of this ModeSet.

        Mode expiration time in seconds  # noqa: E501

        :return: The mode_expiration of this ModeSet.
        :rtype: int
        """
        return self._mode_expiration

    @mode_expiration.setter
    def mode_expiration(self, mode_expiration: int):
        """Sets the mode_expiration of this ModeSet.

        Mode expiration time in seconds  # noqa: E501

        :param mode_expiration: The mode_expiration of this ModeSet.
        :type mode_expiration: int
        """

        self._mode_expiration = mode_expiration
