from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from sovd_server.models.base_model import Model
from sovd_server.models.mode_reference import ModeReference
from sovd_server import util

from sovd_server.models.mode_reference import ModeReference  # noqa: E501

class ModeCollection(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, items=None):  # noqa: E501
        """ModeCollection - a model defined in OpenAPI

        :param items: The items of this ModeCollection.  # noqa: E501
        :type items: List[ModeReference]
        """
        self.openapi_types = {
            'items': List[ModeReference]
        }

        self.attribute_map = {
            'items': 'items'
        }

        self._items = items

    @classmethod
    def from_dict(cls, dikt) -> 'ModeCollection':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ModeCollection of this ModeCollection.  # noqa: E501
        :rtype: ModeCollection
        """
        return util.deserialize_model(dikt, cls)

    @property
    def items(self) -> List[ModeReference]:
        """Gets the items of this ModeCollection.


        :return: The items of this ModeCollection.
        :rtype: List[ModeReference]
        """
        return self._items

    @items.setter
    def items(self, items: List[ModeReference]):
        """Sets the items of this ModeCollection.


        :param items: The items of this ModeCollection.
        :type items: List[ModeReference]
        """
        if items is None:
            raise ValueError("Invalid value for `items`, must not be `None`")  # noqa: E501

        self._items = items
