from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from sovd_server.models.base_model import Model
from sovd_server.models.script_execution_reference import ScriptExecutionReference
from sovd_server import util

from sovd_server.models.script_execution_reference import ScriptExecutionReference  # noqa: E501

class ScriptExecutionCollection(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, items=None):  # noqa: E501
        """ScriptExecutionCollection - a model defined in OpenAPI

        :param items: The items of this ScriptExecutionCollection.  # noqa: E501
        :type items: List[ScriptExecutionReference]
        """
        self.openapi_types = {
            'items': List[ScriptExecutionReference]
        }

        self.attribute_map = {
            'items': 'items'
        }

        self._items = items

    @classmethod
    def from_dict(cls, dikt) -> 'ScriptExecutionCollection':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ScriptExecutionCollection of this ScriptExecutionCollection.  # noqa: E501
        :rtype: ScriptExecutionCollection
        """
        return util.deserialize_model(dikt, cls)

    @property
    def items(self) -> List[ScriptExecutionReference]:
        """Gets the items of this ScriptExecutionCollection.


        :return: The items of this ScriptExecutionCollection.
        :rtype: List[ScriptExecutionReference]
        """
        return self._items

    @items.setter
    def items(self, items: List[ScriptExecutionReference]):
        """Sets the items of this ScriptExecutionCollection.


        :param items: The items of this ScriptExecutionCollection.
        :type items: List[ScriptExecutionReference]
        """
        if items is None:
            raise ValueError("Invalid value for `items`, must not be `None`")  # noqa: E501

        self._items = items
