from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from sovd_server.models.base_model import Model
from sovd_server import util


class ScriptExecutionRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, timeout=None, parameters=None):  # noqa: E501
        """ScriptExecutionRequest - a model defined in OpenAPI

        :param timeout: The timeout of this ScriptExecutionRequest.  # noqa: E501
        :type timeout: int
        :param parameters: The parameters of this ScriptExecutionRequest.  # noqa: E501
        :type parameters: object
        """
        self.openapi_types = {
            'timeout': int,
            'parameters': object
        }

        self.attribute_map = {
            'timeout': 'timeout',
            'parameters': 'parameters'
        }

        self._timeout = timeout
        self._parameters = parameters

    @classmethod
    def from_dict(cls, dikt) -> 'ScriptExecutionRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ScriptExecutionRequest of this ScriptExecutionRequest.  # noqa: E501
        :rtype: ScriptExecutionRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def timeout(self) -> int:
        """Gets the timeout of this ScriptExecutionRequest.

        Execution timeout in seconds  # noqa: E501

        :return: The timeout of this ScriptExecutionRequest.
        :rtype: int
        """
        return self._timeout

    @timeout.setter
    def timeout(self, timeout: int):
        """Sets the timeout of this ScriptExecutionRequest.

        Execution timeout in seconds  # noqa: E501

        :param timeout: The timeout of this ScriptExecutionRequest.
        :type timeout: int
        """

        self._timeout = timeout

    @property
    def parameters(self) -> object:
        """Gets the parameters of this ScriptExecutionRequest.

        Script parameters  # noqa: E501

        :return: The parameters of this ScriptExecutionRequest.
        :rtype: object
        """
        return self._parameters

    @parameters.setter
    def parameters(self, parameters: object):
        """Sets the parameters of this ScriptExecutionRequest.

        Script parameters  # noqa: E501

        :param parameters: The parameters of this ScriptExecutionRequest.
        :type parameters: object
        """

        self._parameters = parameters
