from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from sovd_server.models.base_model import Model
from sovd_server import util


class ScriptExecution(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, status=None, parameters=None, result=None, error=None):  # noqa: E501
        """ScriptExecution - a model defined in OpenAPI

        :param id: The id of this ScriptExecution.  # noqa: E501
        :type id: str
        :param status: The status of this ScriptExecution.  # noqa: E501
        :type status: str
        :param parameters: The parameters of this ScriptExecution.  # noqa: E501
        :type parameters: object
        :param result: The result of this ScriptExecution.  # noqa: E501
        :type result: object
        :param error: The error of this ScriptExecution.  # noqa: E501
        :type error: object
        """
        self.openapi_types = {
            'id': str,
            'status': str,
            'parameters': object,
            'result': object,
            'error': object
        }

        self.attribute_map = {
            'id': 'id',
            'status': 'status',
            'parameters': 'parameters',
            'result': 'result',
            'error': 'error'
        }

        self._id = id
        self._status = status
        self._parameters = parameters
        self._result = result
        self._error = error

    @classmethod
    def from_dict(cls, dikt) -> 'ScriptExecution':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ScriptExecution of this ScriptExecution.  # noqa: E501
        :rtype: ScriptExecution
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this ScriptExecution.


        :return: The id of this ScriptExecution.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this ScriptExecution.


        :param id: The id of this ScriptExecution.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def status(self) -> str:
        """Gets the status of this ScriptExecution.


        :return: The status of this ScriptExecution.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this ScriptExecution.


        :param status: The status of this ScriptExecution.
        :type status: str
        """
        allowed_values = ["running", "completed", "failed", "terminated"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def parameters(self) -> object:
        """Gets the parameters of this ScriptExecution.

        Execution parameters  # noqa: E501

        :return: The parameters of this ScriptExecution.
        :rtype: object
        """
        return self._parameters

    @parameters.setter
    def parameters(self, parameters: object):
        """Sets the parameters of this ScriptExecution.

        Execution parameters  # noqa: E501

        :param parameters: The parameters of this ScriptExecution.
        :type parameters: object
        """

        self._parameters = parameters

    @property
    def result(self) -> object:
        """Gets the result of this ScriptExecution.

        Execution result  # noqa: E501

        :return: The result of this ScriptExecution.
        :rtype: object
        """
        return self._result

    @result.setter
    def result(self, result: object):
        """Sets the result of this ScriptExecution.

        Execution result  # noqa: E501

        :param result: The result of this ScriptExecution.
        :type result: object
        """

        self._result = result

    @property
    def error(self) -> object:
        """Gets the error of this ScriptExecution.

        Error information  # noqa: E501

        :return: The error of this ScriptExecution.
        :rtype: object
        """
        return self._error

    @error.setter
    def error(self, error: object):
        """Sets the error of this ScriptExecution.

        Error information  # noqa: E501

        :param error: The error of this ScriptExecution.
        :type error: object
        """

        self._error = error
