from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from sovd_server.models.base_model import Model
from sovd_server.models.script_reference import ScriptReference
from sovd_server import util

from sovd_server.models.script_reference import ScriptReference  # noqa: E501

class ScriptCollection(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, items=None):  # noqa: E501
        """ScriptCollection - a model defined in OpenAPI

        :param items: The items of this ScriptCollection.  # noqa: E501
        :type items: List[ScriptReference]
        """
        self.openapi_types = {
            'items': List[ScriptReference]
        }

        self.attribute_map = {
            'items': 'items'
        }

        self._items = items

    @classmethod
    def from_dict(cls, dikt) -> 'ScriptCollection':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ScriptCollection of this ScriptCollection.  # noqa: E501
        :rtype: ScriptCollection
        """
        return util.deserialize_model(dikt, cls)

    @property
    def items(self) -> List[ScriptReference]:
        """Gets the items of this ScriptCollection.


        :return: The items of this ScriptCollection.
        :rtype: List[ScriptReference]
        """
        return self._items

    @items.setter
    def items(self, items: List[ScriptReference]):
        """Sets the items of this ScriptCollection.


        :param items: The items of this ScriptCollection.
        :type items: List[ScriptReference]
        """
        if items is None:
            raise ValueError("Invalid value for `items`, must not be `None`")  # noqa: E501

        self._items = items
