from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from sovd_server.models.base_model import Model
from sovd_server import util


class TriggerConditionValuesInner(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self):  # noqa: E501
        """TriggerConditionValuesInner - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'TriggerConditionValuesInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TriggerCondition_values_inner of this TriggerConditionValuesInner.  # noqa: E501
        :rtype: TriggerConditionValuesInner
        """
        return util.deserialize_model(dikt, cls)
