from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from sovd_server.models.base_model import Model
from sovd_server.models.trigger_condition import TriggerCondition
from sovd_server import util

from sovd_server.models.trigger_condition import TriggerCondition  # noqa: E501

class Trigger(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, observed_resource=None, event_source=None, protocol=None, condition=None, lifetime=None):  # noqa: E501
        """Trigger - a model defined in OpenAPI

        :param id: The id of this Trigger.  # noqa: E501
        :type id: str
        :param observed_resource: The observed_resource of this Trigger.  # noqa: E501
        :type observed_resource: str
        :param event_source: The event_source of this Trigger.  # noqa: E501
        :type event_source: str
        :param protocol: The protocol of this Trigger.  # noqa: E501
        :type protocol: str
        :param condition: The condition of this Trigger.  # noqa: E501
        :type condition: TriggerCondition
        :param lifetime: The lifetime of this Trigger.  # noqa: E501
        :type lifetime: int
        """
        self.openapi_types = {
            'id': str,
            'observed_resource': str,
            'event_source': str,
            'protocol': str,
            'condition': TriggerCondition,
            'lifetime': int
        }

        self.attribute_map = {
            'id': 'id',
            'observed_resource': 'observed_resource',
            'event_source': 'event_source',
            'protocol': 'protocol',
            'condition': 'condition',
            'lifetime': 'lifetime'
        }

        self._id = id
        self._observed_resource = observed_resource
        self._event_source = event_source
        self._protocol = protocol
        self._condition = condition
        self._lifetime = lifetime

    @classmethod
    def from_dict(cls, dikt) -> 'Trigger':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Trigger of this Trigger.  # noqa: E501
        :rtype: Trigger
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Trigger.


        :return: The id of this Trigger.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Trigger.


        :param id: The id of this Trigger.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def observed_resource(self) -> str:
        """Gets the observed_resource of this Trigger.


        :return: The observed_resource of this Trigger.
        :rtype: str
        """
        return self._observed_resource

    @observed_resource.setter
    def observed_resource(self, observed_resource: str):
        """Sets the observed_resource of this Trigger.


        :param observed_resource: The observed_resource of this Trigger.
        :type observed_resource: str
        """
        if observed_resource is None:
            raise ValueError("Invalid value for `observed_resource`, must not be `None`")  # noqa: E501

        self._observed_resource = observed_resource

    @property
    def event_source(self) -> str:
        """Gets the event_source of this Trigger.


        :return: The event_source of this Trigger.
        :rtype: str
        """
        return self._event_source

    @event_source.setter
    def event_source(self, event_source: str):
        """Sets the event_source of this Trigger.


        :param event_source: The event_source of this Trigger.
        :type event_source: str
        """
        if event_source is None:
            raise ValueError("Invalid value for `event_source`, must not be `None`")  # noqa: E501

        self._event_source = event_source

    @property
    def protocol(self) -> str:
        """Gets the protocol of this Trigger.


        :return: The protocol of this Trigger.
        :rtype: str
        """
        return self._protocol

    @protocol.setter
    def protocol(self, protocol: str):
        """Sets the protocol of this Trigger.


        :param protocol: The protocol of this Trigger.
        :type protocol: str
        """
        allowed_values = ["sse"]  # noqa: E501
        if protocol not in allowed_values:
            raise ValueError(
                "Invalid value for `protocol` ({0}), must be one of {1}"
                .format(protocol, allowed_values)
            )

        self._protocol = protocol

    @property
    def condition(self) -> TriggerCondition:
        """Gets the condition of this Trigger.


        :return: The condition of this Trigger.
        :rtype: TriggerCondition
        """
        return self._condition

    @condition.setter
    def condition(self, condition: TriggerCondition):
        """Sets the condition of this Trigger.


        :param condition: The condition of this Trigger.
        :type condition: TriggerCondition
        """
        if condition is None:
            raise ValueError("Invalid value for `condition`, must not be `None`")  # noqa: E501

        self._condition = condition

    @property
    def lifetime(self) -> int:
        """Gets the lifetime of this Trigger.

        Trigger lifetime in seconds  # noqa: E501

        :return: The lifetime of this Trigger.
        :rtype: int
        """
        return self._lifetime

    @lifetime.setter
    def lifetime(self, lifetime: int):
        """Sets the lifetime of this Trigger.

        Trigger lifetime in seconds  # noqa: E501

        :param lifetime: The lifetime of this Trigger.
        :type lifetime: int
        """

        self._lifetime = lifetime
