from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from sovd_server.models.base_model import Model
from sovd_server.models.trigger_condition_values_inner import TriggerConditionValuesInner
from sovd_server import util

from sovd_server.models.trigger_condition_values_inner import TriggerConditionValuesInner  # noqa: E501

class TriggerCondition(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, source=None, match='equals', values=None):  # noqa: E501
        """TriggerCondition - a model defined in OpenAPI

        :param source: The source of this TriggerCondition.  # noqa: E501
        :type source: str
        :param match: The match of this TriggerCondition.  # noqa: E501
        :type match: str
        :param values: The values of this TriggerCondition.  # noqa: E501
        :type values: List[TriggerConditionValuesInner]
        """
        self.openapi_types = {
            'source': str,
            'match': str,
            'values': List[TriggerConditionValuesInner]
        }

        self.attribute_map = {
            'source': 'source',
            'match': 'match',
            'values': 'values'
        }

        self._source = source
        self._match = match
        self._values = values

    @classmethod
    def from_dict(cls, dikt) -> 'TriggerCondition':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TriggerCondition of this TriggerCondition.  # noqa: E501
        :rtype: TriggerCondition
        """
        return util.deserialize_model(dikt, cls)

    @property
    def source(self) -> str:
        """Gets the source of this TriggerCondition.

        Source to monitor  # noqa: E501

        :return: The source of this TriggerCondition.
        :rtype: str
        """
        return self._source

    @source.setter
    def source(self, source: str):
        """Sets the source of this TriggerCondition.

        Source to monitor  # noqa: E501

        :param source: The source of this TriggerCondition.
        :type source: str
        """
        if source is None:
            raise ValueError("Invalid value for `source`, must not be `None`")  # noqa: E501

        self._source = source

    @property
    def match(self) -> str:
        """Gets the match of this TriggerCondition.


        :return: The match of this TriggerCondition.
        :rtype: str
        """
        return self._match

    @match.setter
    def match(self, match: str):
        """Sets the match of this TriggerCondition.


        :param match: The match of this TriggerCondition.
        :type match: str
        """
        allowed_values = ["equals", "not_equals", "greater_than", "less_than", "contains"]  # noqa: E501
        if match not in allowed_values:
            raise ValueError(
                "Invalid value for `match` ({0}), must be one of {1}"
                .format(match, allowed_values)
            )

        self._match = match

    @property
    def values(self) -> List[TriggerConditionValuesInner]:
        """Gets the values of this TriggerCondition.


        :return: The values of this TriggerCondition.
        :rtype: List[TriggerConditionValuesInner]
        """
        return self._values

    @values.setter
    def values(self, values: List[TriggerConditionValuesInner]):
        """Sets the values of this TriggerCondition.


        :param values: The values of this TriggerCondition.
        :type values: List[TriggerConditionValuesInner]
        """
        if values is None:
            raise ValueError("Invalid value for `values`, must not be `None`")  # noqa: E501

        self._values = values
