from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from sovd_server.models.base_model import Model
from sovd_server.models.trigger_condition import TriggerCondition
from sovd_server import util

from sovd_server.models.trigger_condition import TriggerCondition  # noqa: E501

class TriggerUpdate(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, condition=None, lifetime=None):  # noqa: E501
        """TriggerUpdate - a model defined in OpenAPI

        :param condition: The condition of this TriggerUpdate.  # noqa: E501
        :type condition: TriggerCondition
        :param lifetime: The lifetime of this TriggerUpdate.  # noqa: E501
        :type lifetime: int
        """
        self.openapi_types = {
            'condition': TriggerCondition,
            'lifetime': int
        }

        self.attribute_map = {
            'condition': 'condition',
            'lifetime': 'lifetime'
        }

        self._condition = condition
        self._lifetime = lifetime

    @classmethod
    def from_dict(cls, dikt) -> 'TriggerUpdate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TriggerUpdate of this TriggerUpdate.  # noqa: E501
        :rtype: TriggerUpdate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def condition(self) -> TriggerCondition:
        """Gets the condition of this TriggerUpdate.


        :return: The condition of this TriggerUpdate.
        :rtype: TriggerCondition
        """
        return self._condition

    @condition.setter
    def condition(self, condition: TriggerCondition):
        """Sets the condition of this TriggerUpdate.


        :param condition: The condition of this TriggerUpdate.
        :type condition: TriggerCondition
        """

        self._condition = condition

    @property
    def lifetime(self) -> int:
        """Gets the lifetime of this TriggerUpdate.

        Trigger lifetime in seconds  # noqa: E501

        :return: The lifetime of this TriggerUpdate.
        :rtype: int
        """
        return self._lifetime

    @lifetime.setter
    def lifetime(self, lifetime: int):
        """Sets the lifetime of this TriggerUpdate.

        Trigger lifetime in seconds  # noqa: E501

        :param lifetime: The lifetime of this TriggerUpdate.
        :type lifetime: int
        """

        self._lifetime = lifetime
