from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from sovd_server.models.base_model import Model
from sovd_server import util


class Version(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, version=None, status=None, accessurl=None):  # noqa: E501
        """Version - a model defined in OpenAPI

        :param version: The version of this Version.  # noqa: E501
        :type version: str
        :param status: The status of this Version.  # noqa: E501
        :type status: str
        :param accessurl: The accessurl of this Version.  # noqa: E501
        :type accessurl: str
        """
        self.openapi_types = {
            'version': str,
            'status': str,
            'accessurl': str
        }

        self.attribute_map = {
            'version': 'version',
            'status': 'status',
            'accessurl': 'accessurl'
        }

        self._version = version
        self._status = status
        self._accessurl = accessurl

    @classmethod
    def from_dict(cls, dikt) -> 'Version':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Version of this Version.  # noqa: E501
        :rtype: Version
        """
        return util.deserialize_model(dikt, cls)

    @property
    def version(self) -> str:
        """Gets the version of this Version.

        Version identifier  # noqa: E501

        :return: The version of this Version.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version: str):
        """Sets the version of this Version.

        Version identifier  # noqa: E501

        :param version: The version of this Version.
        :type version: str
        """
        if version is None:
            raise ValueError("Invalid value for `version`, must not be `None`")  # noqa: E501

        self._version = version

    @property
    def status(self) -> str:
        """Gets the status of this Version.

        Version status  # noqa: E501

        :return: The status of this Version.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this Version.

        Version status  # noqa: E501

        :param status: The status of this Version.
        :type status: str
        """
        allowed_values = ["stable", "draft", "deprecated"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def accessurl(self) -> str:
        """Gets the accessurl of this Version.

        Access URL for this version  # noqa: E501

        :return: The accessurl of this Version.
        :rtype: str
        """
        return self._accessurl

    @accessurl.setter
    def accessurl(self, accessurl: str):
        """Sets the accessurl of this Version.

        Access URL for this version  # noqa: E501

        :param accessurl: The accessurl of this Version.
        :type accessurl: str
        """

        self._accessurl = accessurl
